#!/usr/bin/python3

mysql_db_login = 'mysql -u tg001 -p"f29z70k#r" tg001'
index_path = 'http://student.cryst.bbk.ac.uk/~cd002/index.html'
details_accession_path = 'http://student.cryst.bbk.ac.uk/cgi-bin/cgiwrap/cd002/details.py?radio=accession&query='
favicon_path = 'http://student.cryst.bbk.ac.uk/~cd002/favicon.ico'
logo_path = 'http://student.cryst.bbk.ac.uk/~cd002/logo.svg'
microarray_fig_path = 'http://student.cryst.bbk.ac.uk/~cd002/microarray.jpg'
css_path = 'http://student.cryst.bbk.ac.uk/~cd002/w3.css'
simple_tab_path = 'http://student.cryst.bbk.ac.uk/~cd002/simple_tab.js'
jquery_path = 'http://student.cryst.bbk.ac.uk/~cd002/jquery-3.4.1.min.js'
re_highlight_plugin_path = 'http://student.cryst.bbk.ac.uk/~cd002/jquery.highlight-5.js'
text_highlight_plugin_path = 'http://student.cryst.bbk.ac.uk/~cd002/textHighlight.js'
app_path = 'http://student.cryst.bbk.ac.uk/~cd002/app.js'

# This is dummy data. It shouldn't be necessary with a functional database.
radio = "accession"
typed = "1A"
dna_seq = '''
tctagagatttattcttcttaacaaatgattatccgaattcagttcatttaca<ttcactgctgtagaattcgaatactcagctgtatgaaactagcttaattttttccttattcttc>\
ttttgatatatatttaagttgttgaattctctaattcttcaccattaacaagaat<gctgaattcgcaat>tcatgcctttgtatgtgtcttgtgcaacatagtacatgggttcatcta\
ggctatatatagagagaaggagagaggtttttttgttttttttttgacagagtctcactcagtcacccaggctggagtgcagtggtaaaatttcagctcactgcaacctctacctcctg\
gcttcaagaaatccccccacctcagcctcccaagtagctaggattacatgaaccaccacaccaggctaatttttatttatttattttgtttattttattttatttgaaatggagtctcg\
ctccgtcccc<aggctggagtgcagtggctcaatctcagctcactgcaacctctgcctccctggtttag>agcgattcttctgcccctcagcctcccgagtagctgggattataattgc\
<ctgccaccacgcccggctgatttttgtatatttagtagacacagagttacaccatattggccaggcttatcttgaactcctgaccttctgatccacctgcctcggcatcccaaagtgc\
tggcattacaggcgtgagccaccatgcctggccctatttttatttttttgtaatcttagtagagacagggtttcaccattttactcaggcaggtcttgaactcctcacctcaaatgatc\
tgctccccctcaatcttctaaattgctgggattacaggcatgagccaccgcacctagcctagggta>tatatttaaacatagaattgctaaaataactagatatgg<ccaagtttttcc\
aaaatagttg>taccagtaaacatttgcaacagcatttttgtcatttttatttgtccacatctcactaatcctatgtatttaagaatagttagtatcatttacaataacaaagacatgg\
aaccaacacaaatgcccatcaatgacagactagataaagaaaagtggagctctcgccgcctaatttattggtttataagctctttgttcctaaggcagatgagagcaggaggaagggat\
gaggaaaaggattaatcagtgaaagagaactcatgagtcattcaataagatgtagagcagtagcggtttctgggaatttctttgagcaaaggcatgtgtctaaactacgtaagatcttt\
aacttatagggactgaaatgggtgggagcgggtttcaggaggagccaagacgtttgattatactcccctgcttcaagggactgttatctccctgagcaacctgtggaataccgctgagc\
tgttatgctctcggggcataaagacatgaaggcataaggagacttttctcctcagaggctgccatgctacgcatgggtgtctcacacaggggagaccaactcaactggcaccccagaaa\
ctctctttcccacaagaagtacatggtatacttgcatagccaaagaaattaaaataggccattgaagacagagaaaaacaatggctagaaaaggcagtaggaataaaagagaagatcat\
gcttcctggcttcatggcatgagaatgggggagtgagtagacatccatgagaaaagatcaagggcatgcagccatcggggaaaatccatagtgcagataaagcaaggaggaagaagaag\
gacagttctagtaaaagggagaacatcaatataggatgtttcttagcaatagaaa<aagaaggccaagaggaattagggagagagttataagagatcagc>aaggggacagggttagat\
ttggtttggtttgaaagcatacagtaaatatgatgtctgtccctggcagtgttggcagagtaggaaggaggaaggggaggcaagagataatatcattttctctgtgctccaactgtact\
tacatatgagactatttccctctctgcttttcaaacccttactggagtttgttttccctcatgaaaaccaagaaaggaaagctagttagtcttgttctgaggttgttcaatgtatacat\
atctatatctgtagacagaatccttgggaatacagtaattgacatatattctgttatttgatgcttgaaaaatctcctccactaaccagtttccctatagattgccacaagcacataat\
aagaaacaataaataaaatgttctcttgactttgttacttaacaatgctgagaaaactttacagccttcataaggaagtgaggtccaggaaaatctaggagatatttcttacccaatct\
ataaaggcattagtaatgacaggatatttcctgaaagtgtaatttcccattgaaggatttgtttttaatttctggatccctggagccaatgaagttggtgtatgtttatgaaatatcaa\
gagacataagttggcaagtgttcatatgcaaaaacttcttggaatttctgagttctctgtggcaatatatgacatcaggatatgtccagtctcacacaccaggatatgtcctttctagc\
ctgtctatcacatgctaggagaactatttaggaacagaaaaaaatgcctgaaatgatttctcatttgaactcatccaagctttctctaaatttaagcaaactcctggtcattttcagtt\
agtacctttccttaagttcaaccttcagggcaaacctccgtgcctcaggacgtttagccatagtctgaaattctcttccatagattggtcccctgtaaccccggtttgtctcagcttgt\
tatcctgtttttttcttccctccattcccaggatgagcttgttgcttctgtcctatgagacattagattccttttctttggtacccgagtaaatccatcctactccaatagaggaaggt\
ccatttttgtcttatagcgctggatgcagactcagctgagaagaccattattcatttttggaattctttatctcagatatttcctcttctttctttttcttctatctttggatttttag\
tccatcaacgccccattagtctattccccgacttcaatcagggaacttatacctcttaaactcattcagagactcaaaacatatatattgatacaggagacctaagaagagcatgtctt\
gggggttgaggaaacaggcaggtgagaaatttccagattggaaacacagcttcctttctccc
'''
